### ISSUE TITLE
Issue with cura and CustomSupportCylinder

### ISSUE THREAD

**Issue by psdavidson812** [5axes/CustomSupportCylinder#7]
when using custom support cylinder half of cura blanks out. including a screen shot for reference.
![Screenshot 2021-03-16 110922](https://user-images.githubusercontent.com/80774304/111337024-1c938b00-864c-11eb-884e-bc24fbaad213.png)

**Comment by 5axes** [comment]
Strange .. certainly an issue with the graphics card. But as it is impossible to reproduce this Bug will be not fixed.

**Comment by psdavidson812** [comment]
Thank you for your response. This isn't a graphics card bug. Please see the
inclosed screen shot. It changed the value in the x and y of the scaling.
[image: Screenshot 2021-03-16 125100.png]

**Comment by psdavidson812** [comment]
![Screenshot 2021-03-16 125100](https://user-images.githubusercontent.com/80774304/111349426-7d749080-8657-11eb-9f3c-069eec34bb57.png)

**Comment by 5axes** [comment]
what kind of support are you trying to add to your part ?

**Comment by psdavidson812** [comment]
I have tried them all. So far the first 3 changes the X and Y values. The
last 2 only changes the X value. Changing the size of your supports still
recreates the problem. I thought if maybe I would change the size it may
help. I am using Cura 4.8.0. I have tested several STL and get the same
thing.
Patrick.

**Comment by 5axes** [comment]
Ok As you are the only one for the moment to get this issue and as I cannot reproduce this Error, Wait and see perhap's someone will get the same issue in the futur and will be able to reproduce this error.

I'm Sorry cannot anything else for the moment.

**Comment by psdavidson812** [comment]
Ok, thank you.  Is there a way I can roll back an update? It was working
for me last week and it's an awesome plugin.
Patrick

**Comment by 5axes** [comment]
In the release on this github you have the different release , downloading an older release and use the curapackage (drag ans drop on the curz windows) to install the package

**Comment by psdavidson812** [comment]
I just wanted to give you an update. I reloaded Cura since I was having
problems with another plugin. All is well now, and working great!

**Comment by Lumanet2012** [comment]
Application Version

4.9.1
Platform

Windows 10
Printer

Ender 3
Reproduction steps

Hi everyone,

I am having to print a modified housing for the HERO 5 and I do need to do custom support with 10mm size.
Below the link show's the screenshot of before and after I applied 1 custom support object.

https://owncloud.lumanet.info/s/mboNjAOsUCrUPaw

Somehow when I apply the first custom support object which is a square support everything become a dark gray screen and I no longer can see the object only part of the highlighted object. I am not sure what causes this but it's bugging me because I don't do my job without it working proper.
Actual results

I do only see a small outline of my part and nothing else not even the build plate is visable.
Expected results

I should see my full model with the custom support added but I don't.
Checklist of files to include

Log file
Project file

Additional information & file uploads

2.5.5 Cylindric Custom Support plugin is installed and been used

https://owncloud.lumanet.info/s/mboNjAOsUCrUPaw

All details including log files and all are available too.

**Comment by 5axes** [comment]
I don't think it's an issue comimg from this plugin or Cura itself . Perhap's an issue with the quality of this model at the orgine.
Anyway I cannot reproduce your Issue. Using Cura 4.10. (I have just change the color of the material, using black as color is not a good idea to visualize something in Cura. 

Your Model with 4 square custom support : 
![image](https://user-images.githubusercontent.com/11015345/124006931-1ea30f00-d9db-11eb-86d0-68196b8b5853.png)

This model after the slicing operation : 
![image](https://user-images.githubusercontent.com/11015345/124006993-32e70c00-d9db-11eb-9116-71fef69c8124.png)

**Comment by 5axes** [comment]
If we cannot reproduce it , we cannot fix it

Sorry !

**Comment by Lumanet2012** [comment]
So I thrown out Ultimate and reinstalled and and it's getting worse.  When we used an older version of that plugin it was just fine. So is there an option to downgrade to an older version ?

**Comment by 5axes** [comment]
Yes you will find in the release section certainly an old release, download the curapackage file. Then drag and drop the file in the cura Windows to install the plugin
